# Generated by Django 4.2.2 on 2023-06-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='MIssues',
            field=models.CharField(default='No', max_length=122),
        ),
        migrations.AlterField(
            model_name='person',
            name='lname',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
